### ISSUE TITLE
Unable to update problem archive

### ISSUE THREAD

**Issue by aldoluciano** [fornwall/eclipsecoder#10]
I get the following error:

Failed to download problem stats: String index out of range: -20
String index out of range: -20

Windows 7, Eclipse 4.5.1 64 bit

**Comment by PiyuGandhi** [comment]
Same here
OS: Ubuntu 14.04

**Comment by fornwall** [comment]
Could you try updating to the newly released version 0.3.7 of the archive plug-in?
